FROM mcr.microsoft.com/cbl-mariner/base/core:2.0 AS curlbin
RUN tdnf -y install ca-certificates curl && tdnf clean all

FROM docker.n8n.io/n8nio/n8n
USER root
RUN mkdir -p /etc/ssl/certs
COPY --from=curlbin /usr/bin/curl /usr/bin/curl
COPY --from=curlbin /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
USER node
